# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
    steps: 
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
      - name: Composer install
        run: composer install
      - name: Lancement des tests
        run: php bin/phpunit
