name: Symfony

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: php bin/phpunit

deploy:
  needs: tests
  if: github.ref == 'refs/heads/develop'
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v3
    - name: Deploy to FTP
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        key: ${{ secrets.FTP_SSH_KEY }}
        script: |
          cd /var/www/myapp
          git pull origin develop
          composer install --no-dev
          php bin/console cache:clear 