name: Symfony

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: php bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy on FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          exclude: |
            **/.git/**
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            var/**
            **/.DS_Store
            **/Thumbs.db
          state-name: .ftp-deploy-sync-state.json
          log-level: verbose
          dangerous-clean-slate: true